/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package eheathcaremanagementsystem;
import javax.swing.JFrame;
/**
 *
 * @author Agha
 */
public class AboutUsFrame extends javax.swing.JFrame {

    /**
     * Creates new form AboutUsFrame
     */
    public AboutUsFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AboutUsPanel = new javax.swing.JPanel();
        NidaPicturePanel = new javax.swing.JPanel();
        NidaPictureLabel = new javax.swing.JLabel();
        HiraPicturePanel = new javax.swing.JPanel();
        HiraPictureLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        NidaTextArea = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        HiraTextArea = new javax.swing.JTextArea();
        BackButton = new javax.swing.JButton();
        BackgroundLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        AboutUsPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        NidaPicturePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        NidaPictureLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/eheathcaremanagementsystem/Nida Bitmoji.jpeg"))); // NOI18N
        NidaPicturePanel.add(NidaPictureLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -80, 250, 660));

        AboutUsPanel.add(NidaPicturePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, 240, 250));

        HiraPicturePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        HiraPictureLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/eheathcaremanagementsystem/Hira bitmoji.jpeg"))); // NOI18N
        HiraPictureLabel.setText("jLabel1");
        HiraPicturePanel.add(HiraPictureLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 0, 270, 550));

        AboutUsPanel.add(HiraPicturePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 370, 230, 260));

        NidaTextArea.setEditable(false);
        NidaTextArea.setColumns(20);
        NidaTextArea.setRows(5);
        NidaTextArea.setText("  Hi! I am Nida Javed.\n  My SAP ID is 25296.\n  I am a student of Riphah \n  International University \n  Islambad. And this is our \n  OOP Project. Hope you will\n  like it.");
        jScrollPane1.setViewportView(NidaTextArea);

        AboutUsPanel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 130, 260, 170));

        HiraTextArea.setEditable(false);
        HiraTextArea.setColumns(20);
        HiraTextArea.setRows(5);
        HiraTextArea.setText("Hi! I am Hira Shahzad. \nMy  SAP ID is 24864. \nI am a student of Riphah \nInternational University\nIslamabad. And this is our\nOOP Project. Hope you will\nlike it.");
        jScrollPane2.setViewportView(HiraTextArea);

        AboutUsPanel.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 400, 250, 180));

        BackButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        BackButton.setText("BACK");
        BackButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        BackButton.setOpaque(true);
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });
        AboutUsPanel.add(BackButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 610, 140, 50));

        BackgroundLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/eheathcaremanagementsystem/AboutUsBackground.jpg"))); // NOI18N
        AboutUsPanel.add(BackgroundLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1639, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(AboutUsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(AboutUsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
        // TODO add your handling code here:
        
         MainFrame mf = new MainFrame();
        mf.setVisible(true);
        mf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
      
        
    }//GEN-LAST:event_BackButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AboutUsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AboutUsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AboutUsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AboutUsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AboutUsFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AboutUsPanel;
    private javax.swing.JButton BackButton;
    private javax.swing.JLabel BackgroundLabel;
    private javax.swing.JLabel HiraPictureLabel;
    private javax.swing.JPanel HiraPicturePanel;
    private javax.swing.JTextArea HiraTextArea;
    private javax.swing.JLabel NidaPictureLabel;
    private javax.swing.JPanel NidaPicturePanel;
    private javax.swing.JTextArea NidaTextArea;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
