/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package eheathcaremanagementsystem;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Hira Shazad
 */
public class AdminFrame extends javax.swing.JFrame {

    /**
     * Creates new form AdminFrame
     */
    public AdminFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BackGroundPanel1 = new javax.swing.JPanel();
        A_Label = new javax.swing.JLabel();
        HospitalLabel1 = new javax.swing.JLabel();
        BackGroundPanel2 = new javax.swing.JPanel();
        BackGroundPanel3 = new javax.swing.JPanel();
        A_idLabel = new javax.swing.JLabel();
        A_idTextField = new javax.swing.JTextField();
        A_passLabel = new javax.swing.JLabel();
        A_CheckBox = new javax.swing.JCheckBox();
        A_BackButton = new javax.swing.JButton();
        A_LoginButton = new javax.swing.JButton();
        PassField = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Admin Portal");

        BackGroundPanel1.setBackground(new java.awt.Color(0, 0, 153));

        A_Label.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        A_Label.setForeground(new java.awt.Color(255, 255, 255));
        A_Label.setText("HN Admin Portal");

        HospitalLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/eheathcaremanagementsystem/logo hospital.PNG"))); // NOI18N
        HospitalLabel1.setText("jLabel1");

        javax.swing.GroupLayout BackGroundPanel1Layout = new javax.swing.GroupLayout(BackGroundPanel1);
        BackGroundPanel1.setLayout(BackGroundPanel1Layout);
        BackGroundPanel1Layout.setHorizontalGroup(
            BackGroundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackGroundPanel1Layout.createSequentialGroup()
                .addGroup(BackGroundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BackGroundPanel1Layout.createSequentialGroup()
                        .addGap(568, 568, 568)
                        .addComponent(A_Label))
                    .addGroup(BackGroundPanel1Layout.createSequentialGroup()
                        .addGap(584, 584, 584)
                        .addComponent(HospitalLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(886, Short.MAX_VALUE))
        );
        BackGroundPanel1Layout.setVerticalGroup(
            BackGroundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BackGroundPanel1Layout.createSequentialGroup()
                .addContainerGap(147, Short.MAX_VALUE)
                .addComponent(HospitalLabel1)
                .addGap(18, 18, 18)
                .addComponent(A_Label)
                .addGap(72, 72, 72))
        );

        BackGroundPanel3.setBackground(new java.awt.Color(255, 255, 255));
        BackGroundPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(153, 0, 0), new java.awt.Color(153, 0, 0), new java.awt.Color(153, 0, 0), new java.awt.Color(153, 0, 0)));

        A_idLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/eheathcaremanagementsystem/picture logo.PNG"))); // NOI18N

        A_idTextField.setForeground(new java.awt.Color(204, 204, 204));
        A_idTextField.setText("Admin id");
        A_idTextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                A_idTextFieldMouseClicked(evt);
            }
        });
        A_idTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                A_idTextFieldKeyPressed(evt);
            }
        });

        A_passLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/eheathcaremanagementsystem/pasword logo.PNG"))); // NOI18N

        A_CheckBox.setForeground(new java.awt.Color(153, 0, 0));
        A_CheckBox.setText("View Password");
        A_CheckBox.setContentAreaFilled(false);
        A_CheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A_CheckBoxActionPerformed(evt);
            }
        });

        A_BackButton.setBackground(new java.awt.Color(153, 0, 0));
        A_BackButton.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        A_BackButton.setForeground(new java.awt.Color(255, 255, 255));
        A_BackButton.setText("BACK");
        A_BackButton.setBorderPainted(false);
        A_BackButton.setOpaque(true);
        A_BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A_BackButtonActionPerformed(evt);
            }
        });

        A_LoginButton.setBackground(new java.awt.Color(153, 0, 0));
        A_LoginButton.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        A_LoginButton.setForeground(new java.awt.Color(255, 255, 255));
        A_LoginButton.setText("LOGIN");
        A_LoginButton.setBorderPainted(false);
        A_LoginButton.setOpaque(true);
        A_LoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A_LoginButtonActionPerformed(evt);
            }
        });

        PassField.setForeground(new java.awt.Color(204, 204, 204));
        PassField.setText("Password");
        PassField.setEchoChar('\u0000');
        PassField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PassFieldMouseClicked(evt);
            }
        });
        PassField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PassFieldActionPerformed(evt);
            }
        });
        PassField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                PassFieldKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout BackGroundPanel3Layout = new javax.swing.GroupLayout(BackGroundPanel3);
        BackGroundPanel3.setLayout(BackGroundPanel3Layout);
        BackGroundPanel3Layout.setHorizontalGroup(
            BackGroundPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackGroundPanel3Layout.createSequentialGroup()
                .addComponent(A_CheckBox)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(BackGroundPanel3Layout.createSequentialGroup()
                .addGroup(BackGroundPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BackGroundPanel3Layout.createSequentialGroup()
                        .addGroup(BackGroundPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(A_passLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(A_idLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(BackGroundPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(A_idTextField)
                            .addComponent(PassField)))
                    .addGroup(BackGroundPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(A_BackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                        .addComponent(A_LoginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        BackGroundPanel3Layout.setVerticalGroup(
            BackGroundPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackGroundPanel3Layout.createSequentialGroup()
                .addGroup(BackGroundPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(A_idLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(BackGroundPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(A_idTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(BackGroundPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(A_passLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PassField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(A_CheckBox)
                .addGap(18, 18, 18)
                .addGroup(BackGroundPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(A_BackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(A_LoginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(80, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout BackGroundPanel2Layout = new javax.swing.GroupLayout(BackGroundPanel2);
        BackGroundPanel2.setLayout(BackGroundPanel2Layout);
        BackGroundPanel2Layout.setHorizontalGroup(
            BackGroundPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackGroundPanel2Layout.createSequentialGroup()
                .addGap(515, 515, 515)
                .addComponent(BackGroundPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        BackGroundPanel2Layout.setVerticalGroup(
            BackGroundPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackGroundPanel2Layout.createSequentialGroup()
                .addComponent(BackGroundPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 367, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BackGroundPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(BackGroundPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(BackGroundPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BackGroundPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void A_BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A_BackButtonActionPerformed
        // TODO add your handling code here:
        PanelsFrame hf = new PanelsFrame();
        hf.setVisible(true);
        hf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    }//GEN-LAST:event_A_BackButtonActionPerformed

    private void A_LoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A_LoginButtonActionPerformed
        // TODO add your handling code here:
        
        // Press login button without adding data
        
        // For id
        
          if(A_idTextField.getText().equals("Admin id"))
        {
        A_idTextField.setText(null);
        A_idTextField.setForeground(new java.awt.Color(0, 0, 0));
        A_idTextField.setText("");
        }
         
        // For Password
         
           if(PassField.getText().equals("Password"))
        {
        PassField.setEchoChar('*');
        PassField.setText(null);
        PassField.setForeground(new java.awt.Color(0, 0, 0));
        PassField.setText("");
        }
        
        //Login action 
         
        String id=A_idTextField.getText();
        String passsword=PassField.getText();
        Admin a = new Admin();
        if(id.equalsIgnoreCase(a.getA_id()) && passsword.equals(a.getA_password())){
            JOptionPane.showMessageDialog(this, "Login Succesful");
            AdminMenu am = new AdminMenu();
            am.setVisible(true);
            this.dispose();
        }
        else if(!id.equalsIgnoreCase(a.getA_id()) && passsword.equals(a.getA_password())){
            JOptionPane.showMessageDialog(this, "Invalid id !! Please enter valid id");
            A_idTextField.setText("");
        }
        else if(id.equalsIgnoreCase(a.getA_id())&& !passsword.equals(a.getA_password())){
            JOptionPane.showMessageDialog(this, "Invalid Password !! Please enter valid password");
            PassField.setText("");
        }
        else{
            JOptionPane.showMessageDialog(this, "Invalid id and password");
            A_idTextField.setText("");
            PassField.setText("");
            
        }
        
    }//GEN-LAST:event_A_LoginButtonActionPerformed

    private void A_idTextFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_A_idTextFieldMouseClicked
        // TODO add your handling code here:
        if(A_idTextField.getText().equals("Admin id"))
        {
        A_idTextField.setText(null);
        A_idTextField.setForeground(new java.awt.Color(0, 0, 0));
        A_idTextField.setText("");
        }
    }//GEN-LAST:event_A_idTextFieldMouseClicked

    private void A_CheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A_CheckBoxActionPerformed
        // TODO add your handling code here:
        if(A_CheckBox.isSelected()){
            PassField.setEchoChar((char)0);
        }
        else{
            PassField.setEchoChar('*');
        }
    }//GEN-LAST:event_A_CheckBoxActionPerformed

    private void PassFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PassFieldMouseClicked
        // TODO add your handling code here:
        if(PassField.getText().equals("Password"))
        {
        PassField.setEchoChar('*');
        PassField.setText(null);
        PassField.setForeground(new java.awt.Color(0, 0, 0));
        PassField.setText("");
        }
    }//GEN-LAST:event_PassFieldMouseClicked

    private void A_idTextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_A_idTextFieldKeyPressed
        // TODO add your handling code here:
          if(A_idTextField.getText().equals("Admin id"))
        {
        A_idTextField.setText(null);
        A_idTextField.setForeground(new java.awt.Color(0, 0, 0));
        A_idTextField.setText("");
        }
    }//GEN-LAST:event_A_idTextFieldKeyPressed

    private void PassFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PassFieldKeyPressed
        // TODO add your handling code here:
        if(PassField.getText().equals("Password"))
        {
        PassField.setEchoChar('*');
        PassField.setText(null);
        PassField.setForeground(new java.awt.Color(0, 0, 0));
        PassField.setText("");
        }
    }//GEN-LAST:event_PassFieldKeyPressed

    private void PassFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PassFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PassFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton A_BackButton;
    private javax.swing.JCheckBox A_CheckBox;
    private javax.swing.JLabel A_Label;
    private javax.swing.JButton A_LoginButton;
    private javax.swing.JLabel A_idLabel;
    private javax.swing.JTextField A_idTextField;
    private javax.swing.JLabel A_passLabel;
    private javax.swing.JPanel BackGroundPanel1;
    private javax.swing.JPanel BackGroundPanel2;
    private javax.swing.JPanel BackGroundPanel3;
    private javax.swing.JLabel HospitalLabel1;
    private javax.swing.JPasswordField PassField;
    // End of variables declaration//GEN-END:variables
}
