/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package eheathcaremanagementsystem;

import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Hira Shazad
 */
public class D_PrescriptionFrame extends javax.swing.JFrame {

    /**
     * Creates new form D_PrescriptionFrame
     */
    public D_PrescriptionFrame() {
        initComponents();
    }
    public void displayData(ArrayList <Patient>ap){
         String array[] = new String[6];
         DefaultTableModel tb = (DefaultTableModel)presTable1.getModel();
         for(Patient i: ap){
            array[0] = i.getP_id();
            array[1] = i.getP_name();
            array[2] = i.getP_gender();
            array[3] = i.getP_age()+"";
            array[4] = i.getP_disease();
            array[5] = i.getP_phone_No();
            tb.addRow(array);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        Pres_Id_Label1 = new javax.swing.JLabel();
        id_TF = new javax.swing.JTextField();
        PrescripLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Pres_TA = new javax.swing.JTextArea();
        Back_pres_Button = new javax.swing.JButton();
        add_pres_Button = new javax.swing.JButton();
        Clear_PresButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        DateTF = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        presTable1 = new javax.swing.JTable();
        lable = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        picHF = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Add Prescriptions\n");

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));

        Pres_Id_Label1.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        Pres_Id_Label1.setText("Id of Patient");

        id_TF.setBackground(new java.awt.Color(102, 204, 255));
        id_TF.setForeground(new java.awt.Color(153, 153, 153));
        id_TF.setText("Please Enter Id of Patient");
        id_TF.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                id_TFMouseClicked(evt);
            }
        });

        PrescripLabel2.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        PrescripLabel2.setText("Prescription");

        Pres_TA.setBackground(new java.awt.Color(102, 204, 255));
        Pres_TA.setColumns(20);
        Pres_TA.setForeground(new java.awt.Color(153, 153, 153));
        Pres_TA.setRows(5);
        Pres_TA.setText("Please Enter Prescription of Patient here");
        Pres_TA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Pres_TAMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(Pres_TA);

        Back_pres_Button.setBackground(new java.awt.Color(0, 0, 0));
        Back_pres_Button.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        Back_pres_Button.setForeground(new java.awt.Color(255, 255, 255));
        Back_pres_Button.setText("> Back");
        Back_pres_Button.setBorderPainted(false);
        Back_pres_Button.setOpaque(true);
        Back_pres_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Back_pres_ButtonActionPerformed(evt);
            }
        });

        add_pres_Button.setBackground(new java.awt.Color(0, 0, 0));
        add_pres_Button.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        add_pres_Button.setForeground(new java.awt.Color(255, 255, 255));
        add_pres_Button.setText("Add");
        add_pres_Button.setBorderPainted(false);
        add_pres_Button.setOpaque(true);
        add_pres_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_pres_ButtonActionPerformed(evt);
            }
        });

        Clear_PresButton.setBackground(new java.awt.Color(0, 0, 0));
        Clear_PresButton.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        Clear_PresButton.setForeground(new java.awt.Color(255, 255, 255));
        Clear_PresButton.setText("Clear");
        Clear_PresButton.setBorderPainted(false);
        Clear_PresButton.setOpaque(true);
        Clear_PresButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Clear_PresButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel1.setText("Date");

        DateTF.setBackground(new java.awt.Color(102, 204, 255));
        DateTF.setForeground(new java.awt.Color(153, 153, 153));
        DateTF.setText("Please enter date");
        DateTF.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DateTFMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(Back_pres_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(add_pres_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(130, 130, 130)
                        .addComponent(Clear_PresButton, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(PrescripLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Pres_Id_Label1, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE))
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(101, 101, 101)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(id_TF, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DateTF, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 22, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Pres_Id_Label1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(id_TF, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PrescripLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DateTF, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(add_pres_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Back_pres_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Clear_PresButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(45, 45, 45))))
        );

        presTable1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        presTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Name", "Gender", "Age", "Disease", "Phone No."
            }
        ));
        presTable1.setGridColor(new java.awt.Color(0, 0, 0));
        presTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                presTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(presTable1);
        if (presTable1.getColumnModel().getColumnCount() > 0) {
            presTable1.getColumnModel().getColumn(2).setHeaderValue("Gender");
            presTable1.getColumnModel().getColumn(3).setHeaderValue("Age");
            presTable1.getColumnModel().getColumn(4).setHeaderValue("Disease");
            presTable1.getColumnModel().getColumn(5).setHeaderValue("Phone No.");
        }

        lable.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        lable.setText("List of all patients:");

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Prescription");

        picHF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/eheathcaremanagementsystem/logo hospital.PNG"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(301, 301, 301)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(picHF)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 644, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lable, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(picHF, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE)
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lable, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(93, 93, 93))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Back_pres_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Back_pres_ButtonActionPerformed
        // TODO add your handling code here:
        DoctorMenu dm=new DoctorMenu();
        dm.setVisible(true);
        dm.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    }//GEN-LAST:event_Back_pres_ButtonActionPerformed

    private void id_TFMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_id_TFMouseClicked
        // TODO add your handling code here:
        if(id_TF.getText().equals("Please Enter Id of Patient"))
        {
        id_TF.setForeground(new java.awt.Color(0, 0, 0));
        id_TF.setText("");
        }
    }//GEN-LAST:event_id_TFMouseClicked

    private void Pres_TAMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Pres_TAMouseClicked
        // TODO add your handling code here:
        if(Pres_TA.getText().equals("Please Enter Prescription of Patient here"))
        {
        Pres_TA.setText(null);
        Pres_TA.setForeground(new java.awt.Color(0, 0, 0));
        Pres_TA.setText("");
        }
    }//GEN-LAST:event_Pres_TAMouseClicked

    private void presTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_presTable1MouseClicked
        // TODO add your handling code here:
        DefaultTableModel model=(DefaultTableModel)presTable1.getModel();
        int index=presTable1.getSelectedRow();
        id_TF.setForeground(new java.awt.Color(0, 0, 0));
        id_TF.setText(model.getValueAt(index, 0).toString());
    }//GEN-LAST:event_presTable1MouseClicked
 
    private void add_pres_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_pres_ButtonActionPerformed
        // TODO add your handling code here:
        if(id_TF.getText().isEmpty() || Pres_TA.getText().isEmpty() || id_TF.getText().equalsIgnoreCase("Please Enter Id of Patient") ||Pres_TA.getText().equalsIgnoreCase("Please Enter Prescription of Patient here") ){
           JOptionPane.showMessageDialog(this, "Information Missing");
       }
       else{ 
       String pid = id_TF.getText();
        String did = Pres_TA.getText();
        String time =DateTF.getText();
        //using business class
        Prescription p = new Prescription(pid,did,time);
        //third layer
        PresFileHandler pfh = new PresFileHandler();
        pfh.write(p);
        //using business class
        JOptionPane.showMessageDialog(this, "Prescription is added successfully");
        }
    }//GEN-LAST:event_add_pres_ButtonActionPerformed

    private void DateTFMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DateTFMouseClicked
        // TODO add your handling code here:
        if(DateTF.getText().equals("Please enter date"))
        {
        DateTF.setForeground(new java.awt.Color(0, 0, 0));
        DateTF.setText("");
        }
    }//GEN-LAST:event_DateTFMouseClicked

    private void Clear_PresButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Clear_PresButtonActionPerformed
        // TODO add your handling code here:
        id_TF.setText("");
        Pres_TA.setText("");
        DateTF.setText("");
    }//GEN-LAST:event_Clear_PresButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(D_PrescriptionFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(D_PrescriptionFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(D_PrescriptionFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(D_PrescriptionFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new D_PrescriptionFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back_pres_Button;
    private javax.swing.JButton Clear_PresButton;
    private javax.swing.JTextField DateTF;
    private javax.swing.JLabel Pres_Id_Label1;
    private javax.swing.JTextArea Pres_TA;
    private javax.swing.JLabel PrescripLabel2;
    private javax.swing.JButton add_pres_Button;
    private javax.swing.JTextField id_TF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lable;
    private javax.swing.JLabel picHF;
    private javax.swing.JTable presTable1;
    // End of variables declaration//GEN-END:variables
}
