/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package eheathcaremanagementsystem;

import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Hira Shazad
 */
public class DoctorFrame extends javax.swing.JFrame {

    /**
     * Creates new form DoctorFrame
     */
    public DoctorFrame() {
        initComponents();
    }
     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        dLabel = new javax.swing.JLabel();
        Dlable = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        D_idLabel = new javax.swing.JLabel();
        D_idTextField = new javax.swing.JTextField();
        D_CheckBox = new javax.swing.JCheckBox();
        D_BackButton = new javax.swing.JButton();
        D_loginButton = new javax.swing.JButton();
        D_passLabel = new javax.swing.JLabel();
        PassField = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Doctor Portal\n");

        jPanel1.setBackground(new java.awt.Color(153, 0, 0));
        jPanel1.setForeground(new java.awt.Color(153, 0, 0));

        dLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/eheathcaremanagementsystem/logo hospital.PNG"))); // NOI18N

        Dlable.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        Dlable.setForeground(new java.awt.Color(255, 255, 255));
        Dlable.setText("HN Doctor Portal");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(565, 565, 565)
                        .addComponent(dLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(540, 540, 540)
                        .addComponent(Dlable, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(118, Short.MAX_VALUE)
                .addComponent(dLabel)
                .addGap(18, 18, 18)
                .addComponent(Dlable, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 0, 153), new java.awt.Color(0, 0, 153), new java.awt.Color(0, 0, 153), new java.awt.Color(0, 0, 153)));

        D_idLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/eheathcaremanagementsystem/patient id pic.PNG"))); // NOI18N

        D_idTextField.setForeground(new java.awt.Color(204, 204, 204));
        D_idTextField.setText("Doctor id");
        D_idTextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                D_idTextFieldMouseClicked(evt);
            }
        });
        D_idTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                D_idTextFieldKeyPressed(evt);
            }
        });

        D_CheckBox.setForeground(new java.awt.Color(0, 0, 153));
        D_CheckBox.setText("View Password");
        D_CheckBox.setContentAreaFilled(false);
        D_CheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                D_CheckBoxActionPerformed(evt);
            }
        });

        D_BackButton.setBackground(new java.awt.Color(0, 0, 153));
        D_BackButton.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        D_BackButton.setForeground(new java.awt.Color(255, 255, 255));
        D_BackButton.setText("BACK");
        D_BackButton.setBorderPainted(false);
        D_BackButton.setOpaque(true);
        D_BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                D_BackButtonActionPerformed(evt);
            }
        });

        D_loginButton.setBackground(new java.awt.Color(0, 0, 153));
        D_loginButton.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        D_loginButton.setForeground(new java.awt.Color(255, 255, 255));
        D_loginButton.setText("LOGIN");
        D_loginButton.setBorderPainted(false);
        D_loginButton.setOpaque(true);
        D_loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                D_loginButtonActionPerformed(evt);
            }
        });

        D_passLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/eheathcaremanagementsystem/patient password pic.PNG"))); // NOI18N

        PassField.setForeground(new java.awt.Color(204, 204, 204));
        PassField.setText("Password");
        PassField.setEchoChar('\u0000');
        PassField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PassFieldMouseClicked(evt);
            }
        });
        PassField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                PassFieldKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(D_idLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(D_passLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(D_idTextField)
                            .addComponent(PassField)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(D_CheckBox)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(D_BackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                        .addComponent(D_loginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(D_idTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(D_idLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(D_passLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(PassField, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(35, 35, 35)
                .addComponent(D_CheckBox)
                .addGap(26, 26, 26)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(D_loginButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(D_BackButton, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE))
                .addGap(0, 35, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(494, 494, 494)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(855, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 202, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(97, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void D_BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_D_BackButtonActionPerformed
        // TODO add your handling code here:
        PanelsFrame hf = new PanelsFrame();
        hf.setVisible(true);
        hf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    }//GEN-LAST:event_D_BackButtonActionPerformed

    private void D_loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_D_loginButtonActionPerformed
        // TODO add your handling code here:
        
        // Press login button without adding data
        
        // For id
        
        if(D_idTextField.getText().equals("Doctor id"))
        {
        D_idTextField.setForeground(new java.awt.Color(0, 0, 0));
        D_idTextField.setText("");
        }
        
        // For Password
        
        if(PassField.getText().equals("Password"))
        {
        PassField.setEchoChar('*');
        PassField.setForeground(new java.awt.Color(0, 0, 0));
        PassField.setText("");
        }
        
        // Login action 
       
        String id=D_idTextField.getText();
        String pass=PassField.getText();   
        DoctorFileHandler f = new DoctorFileHandler();
        ArrayList<Doctor>dd= f.read();
        boolean b=false;
        for(Doctor i:dd){
            if(id.equals(i.d_id) && pass.equals(i.password)){
            JOptionPane.showMessageDialog(this, "Login Succesful");
            DoctorMenu dm = new DoctorMenu();
            dm.setVisible(true);
            this.dispose();
            b=true;
            }
        }
        if(b==false){
            JOptionPane.showMessageDialog(this, "Invalid id or password !! Please enter valid id or valid password");
            D_idTextField.setText("");
            PassField.setText("");
        }

    }//GEN-LAST:event_D_loginButtonActionPerformed

    private void D_idTextFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_D_idTextFieldMouseClicked
        // TODO add your handling code here:
        if(D_idTextField.getText().equals("Doctor id"))
        {
        D_idTextField.setText(null);
        D_idTextField.setForeground(new java.awt.Color(0, 0, 0));
        D_idTextField.setText("");
        }
    }//GEN-LAST:event_D_idTextFieldMouseClicked

    private void D_CheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_D_CheckBoxActionPerformed
        // TODO add your handling code here:
        if(D_CheckBox.isSelected()){
            PassField.setEchoChar((char)0);
        }
        else{
            PassField.setEchoChar('*');
        }
    }//GEN-LAST:event_D_CheckBoxActionPerformed

    private void PassFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PassFieldMouseClicked
        // TODO add your handling code here:
        if(PassField.getText().equals("Password"))
        {
        PassField.setEchoChar('*');
        PassField.setForeground(new java.awt.Color(0, 0, 0));
        PassField.setText("");
        }
    }//GEN-LAST:event_PassFieldMouseClicked

    private void D_idTextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_D_idTextFieldKeyPressed
        // TODO add your handling code here:
        if(D_idTextField.getText().equals("Doctor id"))
        {
        D_idTextField.setForeground(new java.awt.Color(0, 0, 0));
        D_idTextField.setText("");
        }
    }//GEN-LAST:event_D_idTextFieldKeyPressed

    private void PassFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PassFieldKeyPressed
        // TODO add your handling code here:
        if(PassField.getText().equals("Password"))
        {
        PassField.setEchoChar('*');;
        PassField.setForeground(new java.awt.Color(0, 0, 0));
        PassField.setText("");
        }
    }//GEN-LAST:event_PassFieldKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DoctorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DoctorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DoctorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DoctorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DoctorFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton D_BackButton;
    private javax.swing.JCheckBox D_CheckBox;
    private javax.swing.JLabel D_idLabel;
    private javax.swing.JTextField D_idTextField;
    private javax.swing.JButton D_loginButton;
    private javax.swing.JLabel D_passLabel;
    private javax.swing.JLabel Dlable;
    private javax.swing.JPasswordField PassField;
    private javax.swing.JLabel dLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
