/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package eheathcaremanagementsystem;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
/**
 *
 * @author Agha
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LogoLabel = new javax.swing.JLabel();
        backgroundPanel = new javax.swing.JPanel();
        InfoLabel1 = new javax.swing.JLabel();
        InfoLabel2 = new javax.swing.JLabel();
        InfoLabel3 = new javax.swing.JLabel();
        InfoLabel4 = new javax.swing.JLabel();
        InfoLabel5 = new javax.swing.JLabel();
        InfoLabel6 = new javax.swing.JLabel();
        InfoLabel7 = new javax.swing.JLabel();
        InfoLabel8 = new javax.swing.JLabel();
        InfoLabel9 = new javax.swing.JLabel();
        panelsButton = new javax.swing.JButton();
        exitButton = new javax.swing.JButton();
        aboutUsButton = new javax.swing.JButton();
        backgroundLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        LogoLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/eheathcaremanagementsystem/Screen-6-4-2021_124615_PM.png"))); // NOI18N

        backgroundPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        InfoLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        InfoLabel1.setForeground(new java.awt.Color(153, 0, 0));
        InfoLabel1.setText("This is E-Health Care Management System user");
        backgroundPanel.add(InfoLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, 470, 40));

        InfoLabel2.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        InfoLabel2.setForeground(new java.awt.Color(153, 0, 0));
        InfoLabel2.setText("interface for managing, monitoring and controlling");
        backgroundPanel.add(InfoLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, 460, 30));

        InfoLabel3.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        InfoLabel3.setForeground(new java.awt.Color(153, 0, 0));
        InfoLabel3.setText("the system in an online hospital. This application is");
        backgroundPanel.add(InfoLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, -1, 30));

        InfoLabel4.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        InfoLabel4.setForeground(new java.awt.Color(153, 0, 0));
        InfoLabel4.setText("developed in java. It focuses on main operations");
        backgroundPanel.add(InfoLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, -1, 30));

        InfoLabel5.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        InfoLabel5.setForeground(new java.awt.Color(153, 0, 0));
        InfoLabel5.setText("in hospital like adding/removing information, doctor");
        backgroundPanel.add(InfoLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 240, -1, 50));

        InfoLabel6.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        InfoLabel6.setForeground(new java.awt.Color(153, 0, 0));
        InfoLabel6.setText("-patient interaction and calculating bills. It features");
        backgroundPanel.add(InfoLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 280, -1, 50));

        InfoLabel7.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        InfoLabel7.setForeground(new java.awt.Color(153, 0, 0));
        InfoLabel7.setText("a familiar and well thought-out and attractive online");
        backgroundPanel.add(InfoLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 320, 480, 50));

        InfoLabel8.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        InfoLabel8.setForeground(new java.awt.Color(153, 0, 0));
        InfoLabel8.setText("user interface. This is our java project of the course");
        backgroundPanel.add(InfoLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 360, 500, 50));

        InfoLabel9.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        InfoLabel9.setForeground(new java.awt.Color(153, 0, 0));
        InfoLabel9.setText("Object Oriented Programming in second semester.");
        backgroundPanel.add(InfoLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 400, -1, 50));

        panelsButton.setBackground(new java.awt.Color(0, 0, 153));
        panelsButton.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        panelsButton.setForeground(new java.awt.Color(255, 255, 255));
        panelsButton.setText("PANELS");
        panelsButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 0), 3));
        panelsButton.setOpaque(true);
        panelsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                panelsButtonActionPerformed(evt);
            }
        });
        backgroundPanel.add(panelsButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 140, 230, 50));

        exitButton.setBackground(new java.awt.Color(0, 0, 153));
        exitButton.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        exitButton.setForeground(new java.awt.Color(255, 255, 255));
        exitButton.setText("EXIT");
        exitButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 0), 3));
        exitButton.setOpaque(true);
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });
        backgroundPanel.add(exitButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 250, 230, 50));

        aboutUsButton.setBackground(new java.awt.Color(0, 0, 153));
        aboutUsButton.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        aboutUsButton.setForeground(new java.awt.Color(255, 255, 255));
        aboutUsButton.setText("About Us");
        aboutUsButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 0), 3));
        aboutUsButton.setOpaque(true);
        aboutUsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutUsButtonActionPerformed(evt);
            }
        });
        backgroundPanel.add(aboutUsButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 360, 230, 50));

        backgroundLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/eheathcaremanagementsystem/medical background.jpg"))); // NOI18N
        backgroundPanel.add(backgroundLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, -220, 1390, 970));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LogoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(backgroundPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(LogoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(backgroundPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 950, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void panelsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_panelsButtonActionPerformed
        // TODO add your handling code here:
        PanelsFrame pf = new PanelsFrame();
        pf.setVisible(true);
        pf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        
    }//GEN-LAST:event_panelsButtonActionPerformed

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        // TODO add your handling code here:
        
        System.exit(0);
    }//GEN-LAST:event_exitButtonActionPerformed

    private void aboutUsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutUsButtonActionPerformed
        // TODO add your handling code here:
        
         AboutUsFrame auf = new AboutUsFrame();
        auf.setVisible(true);
        auf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        
    }//GEN-LAST:event_aboutUsButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel InfoLabel1;
    private javax.swing.JLabel InfoLabel2;
    private javax.swing.JLabel InfoLabel3;
    private javax.swing.JLabel InfoLabel4;
    private javax.swing.JLabel InfoLabel5;
    private javax.swing.JLabel InfoLabel6;
    private javax.swing.JLabel InfoLabel7;
    private javax.swing.JLabel InfoLabel8;
    private javax.swing.JLabel InfoLabel9;
    private javax.swing.JLabel LogoLabel;
    private javax.swing.JButton aboutUsButton;
    private javax.swing.JLabel backgroundLabel;
    private javax.swing.JPanel backgroundPanel;
    private javax.swing.JButton exitButton;
    private javax.swing.JButton panelsButton;
    // End of variables declaration//GEN-END:variables
}
