/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package eheathcaremanagementsystem;
import javax.swing.table.DefaultTableModel;
import java.util.ArrayList;
import javax.swing.JFrame;

/**
 *
 * @author Hira Shazad
 */
public class View_D_Frame extends javax.swing.JFrame {

    /**
     * Creates new form View_D_Frame
     */
    public View_D_Frame() {
        initComponents();
    }
    public void displayData(ArrayList <Doctor>d){
       String array[] = new String[9];
        DefaultTableModel tb = (DefaultTableModel)D_dataTable.getModel();
        for(Doctor i: d){
            array[0] = i.getd_Id()+"";
            array[1] = i.getd_Name();
            array[2] = i.getD_gender();
            array[3] = i.getd_Specialize();
            array[4] = i.getd_PhoneNo();
            array[5] = i.getd_Fee()+"";
            array[6] = i.getd_Time1()+"";
            array[7] = i.getd_Time2()+"";
            array[8] = i.getPassword()+"";
            tb.addRow(array);
        }
    }
     public void deleteData(){
        
        DefaultTableModel tb = (DefaultTableModel)D_dataTable.getModel();
        //jTable1.gets
        int i = D_dataTable.getSelectedRow();
        
        
        String id = tb.getValueAt(i, 0) + "";
        String name = tb.getValueAt(i, 1) + "";
        String gender = tb.getValueAt(i, 2) + "";
        String spec = tb.getValueAt(i, 3) + "";
        String phoneNo = tb.getValueAt(i, 4) + "";
        int fee = Integer.parseInt(tb.getValueAt(i, 5)+"");
        int t1 = Integer.parseInt(tb.getValueAt(i, 6)+"");
        int t2 = Integer.parseInt(tb.getValueAt(i, 7)+"");
        String pass = tb.getValueAt(i, 8) + "";
        System.out.print(id+name+gender+spec+phoneNo+fee+t1+t2+pass);
        Doctor d = new Doctor(id,name,gender,spec,phoneNo,fee,t1,t2,pass);
        DoctorFileHandler dfh = new DoctorFileHandler();
        dfh.delete(d);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        D_MainButton = new javax.swing.JButton();
        D_BackButton3 = new javax.swing.JButton();
        picLabel3 = new javax.swing.JLabel();
        RefreshButton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        D_dataTable = new javax.swing.JTable();
        D_listLabel = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        D_AddButton1 = new javax.swing.JButton();
        pic = new javax.swing.JLabel();
        Navagtion = new javax.swing.JLabel();
        DeletButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("View Doctors List");
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel3.setBackground(new java.awt.Color(204, 204, 255));

        D_MainButton.setBackground(new java.awt.Color(51, 51, 51));
        D_MainButton.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        D_MainButton.setForeground(new java.awt.Color(255, 255, 255));
        D_MainButton.setText("Main Menu");
        D_MainButton.setBorderPainted(false);
        D_MainButton.setOpaque(true);
        D_MainButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                D_MainButtonActionPerformed(evt);
            }
        });

        D_BackButton3.setBackground(new java.awt.Color(51, 51, 51));
        D_BackButton3.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        D_BackButton3.setForeground(new java.awt.Color(255, 255, 255));
        D_BackButton3.setText("Back ");
        D_BackButton3.setBorderPainted(false);
        D_BackButton3.setOpaque(true);
        D_BackButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                D_BackButton3ActionPerformed(evt);
            }
        });

        picLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/eheathcaremanagementsystem/Doctors illustration.png"))); // NOI18N

        RefreshButton.setBackground(new java.awt.Color(51, 51, 51));
        RefreshButton.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        RefreshButton.setForeground(new java.awt.Color(255, 255, 255));
        RefreshButton.setText("Refresh Data");
        RefreshButton.setBorderPainted(false);
        RefreshButton.setOpaque(true);
        RefreshButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RefreshButtonActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(51, 51, 51));
        jButton1.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Update Data");
        jButton1.setBorderPainted(false);
        jButton1.setOpaque(true);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(picLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(D_BackButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
                            .addComponent(D_MainButton, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
                            .addComponent(RefreshButton, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(RefreshButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(D_BackButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(D_MainButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(picLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7))
        );

        D_dataTable.setBackground(new java.awt.Color(204, 204, 255));
        D_dataTable.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        D_dataTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Name", "Gender", "Specialization", "Phone No.", "Fee", "Start time", "End time", "Password"
            }
        ));
        jScrollPane1.setViewportView(D_dataTable);
        if (D_dataTable.getColumnModel().getColumnCount() > 0) {
            D_dataTable.getColumnModel().getColumn(7).setResizable(false);
        }

        D_listLabel.setBackground(new java.awt.Color(255, 255, 255));
        D_listLabel.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        D_listLabel.setText("List of Doctors");

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 225, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 26, Short.MAX_VALUE)
        );

        D_AddButton1.setBackground(new java.awt.Color(51, 51, 51));
        D_AddButton1.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        D_AddButton1.setForeground(new java.awt.Color(255, 255, 255));
        D_AddButton1.setText("Add Doctors");
        D_AddButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 0, 51), new java.awt.Color(255, 0, 51), new java.awt.Color(255, 0, 51), new java.awt.Color(255, 0, 51)));
        D_AddButton1.setBorderPainted(false);
        D_AddButton1.setOpaque(true);
        D_AddButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                D_AddButton1ActionPerformed(evt);
            }
        });

        pic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/eheathcaremanagementsystem/Doctor Add.PNG"))); // NOI18N

        Navagtion.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Navagtion.setText("Navigation");

        DeletButton.setBackground(new java.awt.Color(51, 51, 51));
        DeletButton.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        DeletButton.setForeground(new java.awt.Color(255, 255, 255));
        DeletButton.setText("Delete Data");
        DeletButton.setBorderPainted(false);
        DeletButton.setOpaque(true);
        DeletButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeletButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(DeletButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(pic, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(29, 29, 29)
                                    .addComponent(Navagtion))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(D_AddButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Navagtion, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(D_AddButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pic, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(DeletButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 99, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(D_listLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 998, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(431, 431, 431))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(D_listLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 667, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(226, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void D_BackButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_D_BackButton3ActionPerformed
        // TODO add your handling code here:
        AdminMenu am = new AdminMenu();
        am.setVisible(true);
        am.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    }//GEN-LAST:event_D_BackButton3ActionPerformed

    private void D_MainButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_D_MainButtonActionPerformed
        // TODO add your handling code here:
        MainFrame mf = new MainFrame();
        mf.setVisible(true);
        mf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    }//GEN-LAST:event_D_MainButtonActionPerformed

    private void D_AddButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_D_AddButton1ActionPerformed
        // TODO add your handling code here:
        DoctorDataForm ddf=new DoctorDataForm();
        ddf.setVisible(true);
        ddf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    }//GEN-LAST:event_D_AddButton1ActionPerformed

    private void DeletButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeletButtonActionPerformed
        // TODO add your handling code here:
        deleteData();
    }//GEN-LAST:event_DeletButtonActionPerformed

    private void RefreshButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RefreshButtonActionPerformed
        // TODO add your handling code here:
        DefaultTableModel tb = (DefaultTableModel)D_dataTable.getModel();
        tb.setRowCount(0);
        DoctorFileHandler dfh = new DoctorFileHandler();
        ArrayList <Doctor> d = dfh.read();
        this.displayData(d);
    }//GEN-LAST:event_RefreshButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
          DefaultTableModel tb = (DefaultTableModel)D_dataTable.getModel();
        //jTable1.gets
        int i = D_dataTable.getSelectedRow();
        
        String id = tb.getValueAt(i, 0) + "";
        String name = tb.getValueAt(i, 1) + "";
        String gender = tb.getValueAt(i, 2) + "";
        String spec = tb.getValueAt(i, 3) + "";
        String phNo = tb.getValueAt(i, 4) + "";
        int fee = Integer.parseInt(tb.getValueAt(i, 5)+"");
        int t1 = Integer.parseInt(tb.getValueAt(i, 6)+"");
        int t2 = Integer.parseInt(tb.getValueAt(i, 7)+"");
        String pass = tb.getValueAt(i, 8) + "";
        System.out.print(id+name+gender+spec+phNo+fee+t1+t2+pass);
        Doctor d = new Doctor(id,name,gender,spec,phNo,fee,t1,t2,pass);
        DoctorFileHandler dfh = new DoctorFileHandler();
        dfh.update(d);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(View_D_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(View_D_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(View_D_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(View_D_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new View_D_Frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton D_AddButton1;
    private javax.swing.JButton D_BackButton3;
    private javax.swing.JButton D_MainButton;
    private javax.swing.JTable D_dataTable;
    private javax.swing.JLabel D_listLabel;
    private javax.swing.JButton DeletButton;
    private javax.swing.JLabel Navagtion;
    private javax.swing.JButton RefreshButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel pic;
    private javax.swing.JLabel picLabel3;
    // End of variables declaration//GEN-END:variables
}
