/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package eheathcaremanagementsystem;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import javax.swing.JFrame;

/**
 *
 * @author Hira Shahzad and Nida javed
 */
public class View_p_Frame extends javax.swing.JFrame {

    /**
     * Creates new form View_p_Frame
     */
    public View_p_Frame() {
        initComponents();
    }
    
     public void displayData(ArrayList <Patient>p){
         String array[] = new String[6];
         DefaultTableModel tb = (DefaultTableModel)P_Table1.getModel();
         for(Patient i: p){
            array[0] = i.getP_id();
            array[1] = i.getP_name();
            array[2] = i.getP_gender();
            array[3] = i.getP_age()+"";
            array[4] = i.getP_disease();
            array[5] = i.getP_phone_No();
            tb.addRow(array);
        }
    }
     public void deleteData(){
        DefaultTableModel tb = (DefaultTableModel)P_Table1.getModel();
        //jTable1.gets
        int i = P_Table1.getSelectedRow();
        
        String id = tb.getValueAt(i, 0) + "";
        String name = tb.getValueAt(i, 1) + "";
        String gender = tb.getValueAt(i, 2) + "";
        int age = Integer.parseInt(tb.getValueAt(i, 3)+"");
        String disease = tb.getValueAt(i, 4) + "";
        String phoneNo = tb.getValueAt(i, 5) + "";
        System.out.print(name+id+age);
        Patient p = new Patient(id,name,gender,age,disease,phoneNo);
        PatientFileHandler pfh = new PatientFileHandler();
        pfh.delete(p);
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        P_Table1 = new javax.swing.JTable();
        P_ListLabel = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        P_navigateLabel = new javax.swing.JLabel();
        P_AddButton = new javax.swing.JButton();
        P_AddLabel = new javax.swing.JLabel();
        P_DeletButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        P_MainMenuButton = new javax.swing.JButton();
        PicLabel4 = new javax.swing.JLabel();
        P_BackButton = new javax.swing.JButton();
        RefreshButton = new javax.swing.JButton();
        UpdateButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("View Patients List");

        P_Table1.setBackground(new java.awt.Color(204, 204, 255));
        P_Table1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id ", "Name ", "Gender ", "Age", "Disease", "Phone No."
            }
        ));
        jScrollPane1.setViewportView(P_Table1);
        if (P_Table1.getColumnModel().getColumnCount() > 0) {
            P_Table1.getColumnModel().getColumn(0).setPreferredWidth(3);
            P_Table1.getColumnModel().getColumn(1).setPreferredWidth(4);
            P_Table1.getColumnModel().getColumn(2).setPreferredWidth(1);
            P_Table1.getColumnModel().getColumn(3).setPreferredWidth(1);
        }

        P_ListLabel.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        P_ListLabel.setText("List of Patients");

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 221, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 29, Short.MAX_VALUE)
        );

        P_navigateLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        P_navigateLabel.setText("Navigation");

        P_AddButton.setBackground(new java.awt.Color(51, 51, 51));
        P_AddButton.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        P_AddButton.setForeground(new java.awt.Color(255, 255, 255));
        P_AddButton.setText("Add Appointment");
        P_AddButton.setBorderPainted(false);
        P_AddButton.setOpaque(true);
        P_AddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                P_AddButtonActionPerformed(evt);
            }
        });

        P_AddLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/eheathcaremanagementsystem/Doctor Add.PNG"))); // NOI18N

        P_DeletButton.setBackground(new java.awt.Color(51, 51, 51));
        P_DeletButton.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        P_DeletButton.setForeground(new java.awt.Color(255, 255, 255));
        P_DeletButton.setText("Delete Data");
        P_DeletButton.setBorderPainted(false);
        P_DeletButton.setOpaque(true);
        P_DeletButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                P_DeletButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(P_DeletButton, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(P_AddLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(P_navigateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(P_AddButton))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(P_navigateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(P_AddButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(P_AddLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(P_DeletButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));

        P_MainMenuButton.setBackground(new java.awt.Color(51, 51, 51));
        P_MainMenuButton.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        P_MainMenuButton.setForeground(new java.awt.Color(255, 255, 255));
        P_MainMenuButton.setText("Main Menu");
        P_MainMenuButton.setBorderPainted(false);
        P_MainMenuButton.setOpaque(true);
        P_MainMenuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                P_MainMenuButtonActionPerformed(evt);
            }
        });

        PicLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/eheathcaremanagementsystem/Patient illustration (1).png"))); // NOI18N

        P_BackButton.setBackground(new java.awt.Color(51, 51, 51));
        P_BackButton.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        P_BackButton.setForeground(new java.awt.Color(255, 255, 255));
        P_BackButton.setText("Back");
        P_BackButton.setBorderPainted(false);
        P_BackButton.setOpaque(true);
        P_BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                P_BackButtonActionPerformed(evt);
            }
        });

        RefreshButton.setBackground(new java.awt.Color(51, 51, 51));
        RefreshButton.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        RefreshButton.setForeground(new java.awt.Color(255, 255, 255));
        RefreshButton.setText("Refresh Data");
        RefreshButton.setBorderPainted(false);
        RefreshButton.setOpaque(true);
        RefreshButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RefreshButtonActionPerformed(evt);
            }
        });

        UpdateButton.setBackground(new java.awt.Color(51, 51, 51));
        UpdateButton.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        UpdateButton.setForeground(new java.awt.Color(255, 255, 255));
        UpdateButton.setText("Update Data");
        UpdateButton.setBorderPainted(false);
        UpdateButton.setOpaque(true);
        UpdateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PicLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(UpdateButton, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)
                            .addComponent(RefreshButton, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)
                            .addComponent(P_MainMenuButton, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)
                            .addComponent(P_BackButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(RefreshButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(UpdateButton, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(P_BackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(P_MainMenuButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(PicLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 177, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(P_ListLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1022, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(65, 65, 65))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(P_ListLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 574, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(52, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void P_MainMenuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_P_MainMenuButtonActionPerformed
        // TODO add your handling code here:
        MainFrame mf = new MainFrame();
        mf.setVisible(true);
        mf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    }//GEN-LAST:event_P_MainMenuButtonActionPerformed

    private void P_BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_P_BackButtonActionPerformed
        // TODO add your handling code here:
        AdminMenu am = new AdminMenu();
        am.setVisible(true);
        am.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    }//GEN-LAST:event_P_BackButtonActionPerformed

    private void P_AddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_P_AddButtonActionPerformed
        // TODO add your handling code here:
       AddAppointmentFrame aaf = new AddAppointmentFrame();
        aaf.setVisible(true);
        aaf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    }//GEN-LAST:event_P_AddButtonActionPerformed

    private void P_DeletButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_P_DeletButtonActionPerformed
        // TODO add your handling code here:
        deleteData();
    }//GEN-LAST:event_P_DeletButtonActionPerformed

    private void RefreshButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RefreshButtonActionPerformed
        // TODO add your handling code here:
        DefaultTableModel tb = (DefaultTableModel)P_Table1.getModel();
        tb.setRowCount(0);
        PatientFileHandler pfh = new PatientFileHandler();
        ArrayList <Patient> p = pfh.read();
        this.displayData(p);
    }//GEN-LAST:event_RefreshButtonActionPerformed

    private void UpdateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateButtonActionPerformed
        // TODO add your handling code here:
        DefaultTableModel tb = (DefaultTableModel)P_Table1.getModel();
        //jTable1.gets
        int i = P_Table1.getSelectedRow();
        String id = tb.getValueAt(i, 0) + "";
        String name = tb.getValueAt(i, 1) + "";
        String gender = tb.getValueAt(i, 2) + "";
        int age = Integer.parseInt(tb.getValueAt(i, 3)+"");
        String disease = tb.getValueAt(i, 4) + "";
        String phoneNo = tb.getValueAt(i, 5) + "";
        System.out.print(name+id+age);
        Patient p = new Patient(id,name,gender,age,disease,phoneNo);
        PatientFileHandler pfh = new PatientFileHandler();
        pfh.update(p);
    }//GEN-LAST:event_UpdateButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(View_p_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(View_p_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(View_p_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(View_p_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new View_p_Frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton P_AddButton;
    private javax.swing.JLabel P_AddLabel;
    private javax.swing.JButton P_BackButton;
    private javax.swing.JButton P_DeletButton;
    private javax.swing.JLabel P_ListLabel;
    private javax.swing.JButton P_MainMenuButton;
    private javax.swing.JTable P_Table1;
    private javax.swing.JLabel P_navigateLabel;
    private javax.swing.JLabel PicLabel4;
    private javax.swing.JButton RefreshButton;
    private javax.swing.JButton UpdateButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
